// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKfBT_bIJ7g0JCjKIKN8zGbWfSfW9rrIk',
    appId: '1:255429867066:web:26341056afcd141ce1a703',
    messagingSenderId: '255429867066',
    projectId: 'my-flutter-ai-app-73872',
    authDomain: 'my-flutter-ai-app-73872.firebaseapp.com',
    storageBucket: 'my-flutter-ai-app-73872.firebasestorage.app',
    measurementId: 'G-T3WT7371KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp74r2pDMGByLv0qvrgEgRcu8I01bqcvI',
    appId: '1:255429867066:android:dd5af9f61d17d2a6e1a703',
    messagingSenderId: '255429867066',
    projectId: 'my-flutter-ai-app-73872',
    storageBucket: 'my-flutter-ai-app-73872.firebasestorage.app',
  );

}